# ============================================================================
# MarkdownReport.jl — Human-readable .REPORT.md writer for every solve.
#
# Included at the top level of OpenJFEM (after Export.jl), so all
# exporter symbols it needs (`_export_base_name`, etc.) are in scope.
#
# Public entry: export_markdown_report(results, filename, output_dir; timings)
# ============================================================================

# ---- formatting helpers -------------------------------------------------

@inline function _report_fmt_time(s)
    s = Float64(s)
    if !isfinite(s) || s < 0
        return "—"
    elseif s < 1.0
        return @sprintf("%.3f s", s)
    elseif s < 60.0
        return @sprintf("%.2f s", s)
    else
        m = floor(Int, s / 60)
        r = s - 60m
        return @sprintf("%.1f s  (%dm %04.1fs)", s, m, r)
    end
end

@inline function _report_fmt_sci(x)
    x = Float64(x)
    isfinite(x) || return "—"
    abs_x = abs(x)
    if abs_x == 0.0
        return "0"
    elseif abs_x < 1e-3 || abs_x >= 1e5
        return @sprintf("%.6e", x)
    else
        return @sprintf("%.6f", x)
    end
end

@inline function _report_fmt_float(x; digits=6)
    x = Float64(x)
    isfinite(x) || return "—"
    return @sprintf("%.*f", digits, x)
end

@inline _report_safe_get(d, key, default) = (d isa AbstractDict && haskey(d, key)) ? d[key] : default

# ---- top-level entry ----------------------------------------------------

"""
    export_markdown_report(results, filename, output_dir; timings=nothing)

Write a human-readable `.REPORT.md` next to the other outputs. Contains
step-level timing, a mesh summary, and per-SOL quality/result tables.
`timings` is an optional `Dict{String,Float64}` of pipeline-level stage
durations in seconds (supplied by `main()`); per-solve timings stashed
inside `results["timings"]` are merged automatically.
"""
function export_markdown_report(results::AbstractDict, filename::AbstractString,
                                output_dir::AbstractString; timings=nothing)
    md_path = joinpath(output_dir, _export_base_name(filename) * ".REPORT.md")
    println("\n>>> Exporting MARKDOWN REPORT: $md_path")

    merged_timings = Dict{String,Any}()
    if timings isa AbstractDict
        for (k, v) in timings; merged_timings[string(k)] = v; end
    end
    solve_timings = _report_safe_get(results, "timings", Dict{String,Any}())
    if solve_timings isa AbstractDict
        for (k, v) in solve_timings; merged_timings[string(k)] = v; end
    end

    sol_type = Int(_report_safe_get(results, "sol_type", 0))
    analysis_type = string(_report_safe_get(results, "analysis_type", _sol_type_label(sol_type)))

    open(md_path, "w") do io
        _report_header(io, filename, sol_type, analysis_type)
        _report_environment_section(io)
        _report_timing_section(io, merged_timings)
        _report_mesh_section(io, results)

        if sol_type == 101
            _report_sol101_section(io, results)
        elseif sol_type == 103
            _report_sol103_section(io, results)
        elseif sol_type == 105
            _report_sol105_section(io, results)
        elseif sol_type == 106
            _report_sol106_section(io, results)
        elseif sol_type == 200
            _report_sol200_section(io, results)
        else
            println(io, "## Results")
            println(io, "\n_Unknown SOL type ($sol_type). No tailored report available._")
        end

        println(io, "\n---")
        println(io, "_Report generated by OpenJFEM._")
    end
    return md_path
end

@inline function _sol_type_label(sol_type::Int)
    sol_type == 101 && return "SOL 101 — Linear Static"
    sol_type == 103 && return "SOL 103 — Normal Modes"
    sol_type == 105 && return "SOL 105 — Linear Buckling"
    sol_type == 106 && return "SOL 106 — Nonlinear Static"
    sol_type == 200 && return "SOL 200 — Design Optimization"
    return "SOL $(sol_type)"
end

# ---- header -------------------------------------------------------------

function _report_header(io, filename, sol_type, analysis_type)
    stamp = Dates.format(Dates.now(), "yyyy-mm-dd HH:MM:SS")
    println(io, "# OpenJFEM Analysis Report")
    println(io)
    println(io, "| Field | Value |")
    println(io, "|---|---|")
    println(io, "| Input file   | `", basename(filename), "` |")
    println(io, "| Analysis     | ", analysis_type, " |")
    println(io, "| SOL type     | ", sol_type, " |")
    println(io, "| Generated    | ", stamp, " |")
    println(io)
end

# ---- environment provenance --------------------------------------------

function _report_md_table_cell(x)
    s = string(x)
    s = replace(s, "\r" => " ")
    s = replace(s, "\n" => " ")
    s = replace(s, "|" => "\\|")
    s = replace(s, "`" => "\\`")
    return s
end

function _report_environment_section(io)
    jfem_keys = sort!([String(k) for (k, _) in ENV if startswith(String(k), "JFEM_")])
    println(io, "## Solver environment")
    println(io)
    println(io, "| Setting | Value |")
    println(io, "|---|---|")
    println(io, "| `Julia threads` | `", Threads.nthreads(), "` |")
    if isempty(jfem_keys)
        println(io, "| `JFEM_*` | _none set in this process_ |")
    else
        for key in jfem_keys
            println(io, "| `", _report_md_table_cell(key), "` | `",
                    _report_md_table_cell(get(ENV, key, "")), "` |")
        end
    end
    println(io)
end

# ---- timing section -----------------------------------------------------

const _REPORT_TIMING_ORDER = [
    ("parse",        "BDF parsing"),
    ("build_model",  "Model construction"),
    ("solve",        "Solve (total)"),
    ("assembly_K",   "  stiffness assembly"),
    ("assembly_Keig","  stiffness re-assembly (SOL 105 eig path)"),
    ("solve_cases",  "  case/subcase solves"),
    ("export",       "Export (all formats)"),
]

function _report_timing_section(io, timings)
    println(io, "## Pipeline timing")
    println(io)
    if isempty(timings)
        println(io, "_No timing information captured._\n")
        return
    end
    println(io, "| Stage | Wall time |")
    println(io, "|---|---:|")

    total = 0.0
    seen = Set{String}()
    for (key, label) in _REPORT_TIMING_ORDER
        haskey(timings, key) || continue
        s = Float64(timings[key])
        println(io, "| ", label, " | ", _report_fmt_time(s), " |")
        push!(seen, key)
        # only top-level stages contribute to total (children are indented with 2 leading spaces)
        if !startswith(label, "  ")
            total += s
        end
    end
    # any extra keys we didn't anticipate
    for k in sort!(collect(keys(timings)))
        k in seen && continue
        println(io, "| ", k, " | ", _report_fmt_time(timings[k]), " |")
    end
    println(io, "| **Total (non-overlapping stages)** | **", _report_fmt_time(total), "** |")
    println(io)
end

# ---- mesh section -------------------------------------------------------

function _report_mesh_section(io, results)
    mesh = _report_safe_get(results, "mesh", nothing)
    println(io, "## Mesh")
    println(io)
    if mesh === nothing
        println(io, "_No mesh summary available._\n")
        return
    end
    n_nodes = length(_report_safe_get(mesh, "nodes", []))
    n_quads = length(_report_safe_get(mesh, "quads", []))
    n_trias = length(_report_safe_get(mesh, "trias", []))
    n_bars  = length(_report_safe_get(mesh, "bars",  []))
    n_rods  = length(_report_safe_get(mesh, "rods",  []))
    n_solids = length(_report_safe_get(mesh, "solids", []))
    ndof = Int(_report_safe_get(results, "ndof", 6 * n_nodes))

    println(io, "| Entity | Count |")
    println(io, "|---|---:|")
    println(io, "| Nodes        | ", n_nodes, " |")
    println(io, "| DOFs         | ", ndof, " |")
    println(io, "| QUAD shells  | ", n_quads, " |")
    println(io, "| TRIA shells  | ", n_trias, " |")
    println(io, "| Bar/Beam     | ", n_bars, " |")
    println(io, "| Rod          | ", n_rods, " |")
    println(io, "| Solids       | ", n_solids, " |")
    println(io)
end

# ---- SOL 101 ------------------------------------------------------------

function _report_sol101_section(io, results)
    println(io, "## SOL 101 — Linear Static Results")
    println(io)
    subcases = _report_safe_get(results, "subcases", [])
    if isempty(subcases)
        println(io, "_No subcases solved._\n")
        return
    end
    for sc in subcases
        sid = _report_safe_get(sc, "sid", "?")
        println(io, "### Subcase ", sid)
        println(io)
        _report_write_static_quality(io, sc)
        println(io)
    end
end

function _report_write_static_quality(io, sc::AbstractDict)
    u = _report_safe_get(sc, "raw_displacement", Float64[])
    disps = _report_safe_get(sc, "displacements", [])
    max_trans_val, max_trans_id = _report_peak_disp(disps, :trans)
    max_rot_val, max_rot_id = _report_peak_disp(disps, :rot)

    stresses = _report_safe_get(sc, "element_vonmises", Dict{Int,Float64}())
    vm_val, vm_id = _report_peak_vonmises(stresses)

    diag = _report_safe_get(sc, "solver_diagnostics", Dict{String,Any}())
    ls = _report_safe_get(diag, "linear_solver", Dict{String,Any}())
    eq = _report_safe_get(diag, "equilibrium", Dict{String,Any}())
    reac = _report_safe_get(eq, "spc_reaction_sum", Dict("fx"=>0.0,"fy"=>0.0,"fz"=>0.0))

    println(io, "**Displacements**")
    println(io)
    println(io, "| Quantity | Value | Grid |")
    println(io, "|---|---:|---:|")
    println(io, "| Peak \\|translation\\| | ", _report_fmt_sci(max_trans_val), " | ", max_trans_id, " |")
    println(io, "| Peak \\|rotation\\|    | ", _report_fmt_sci(max_rot_val),   " | ", max_rot_id,   " |")
    if u isa AbstractVector && !isempty(u)
        println(io, "| \\|u\\|₂               | ", _report_fmt_sci(norm(u)),   " | — |")
    end
    println(io)

    println(io, "**Peak von Mises stress**")
    println(io)
    println(io, "| Value | Element |")
    println(io, "|---:|---:|")
    println(io, "| ", _report_fmt_sci(vm_val), " | ", vm_id, " |")
    println(io)

    println(io, "**Equilibrium & linear solver**")
    println(io)
    println(io, "| Quantity | Value |")
    println(io, "|---|---:|")
    println(io, "| SPC reaction sum Fx | ", _report_fmt_sci(reac["fx"]), " |")
    println(io, "| SPC reaction sum Fy | ", _report_fmt_sci(reac["fy"]), " |")
    println(io, "| SPC reaction sum Fz | ", _report_fmt_sci(reac["fz"]), " |")
    println(io, "| Reaction residual (‖·‖) | ", _report_fmt_sci(_report_safe_get(eq, "residual", 0.0)), " |")
    println(io, "| Linear-solver rel. residual | ", _report_fmt_sci(_report_safe_get(ls, "relative_residual", 0.0)), " |")
    println(io, "| Linear-solver force norm | ", _report_fmt_sci(_report_safe_get(ls, "force_norm", 0.0)), " |")
    println(io, "| Backend | `", _report_safe_get(ls, "backend", "?"), "` |")
    println(io, "| Strategy | `", _report_safe_get(ls, "strategy", "?"), "` |")
    println(io, "| Cache hit | ", _report_safe_get(ls, "cache_hit", false), " |")
    wall = _report_safe_get(sc, "wall_seconds", nothing)
    if !isnothing(wall)
        println(io, "| Subcase wall time | ", _report_fmt_time(wall), " |")
    end
end

function _report_peak_disp(disps, kind::Symbol)
    keys_mag = kind === :trans ? ("t1","t2","t3") : ("r1","r2","r3")
    best = 0.0; best_id = -1
    for d in disps
        d isa AbstractDict || continue
        v = sqrt(sum(Float64(get(d, k, 0.0))^2 for k in keys_mag))
        if v > best
            best = v
            best_id = get(d, "grid_id", -1)
        end
    end
    return best, best_id
end

function _report_peak_vonmises(stresses)
    best = 0.0; best_id = -1
    if stresses isa AbstractDict
        for (eid, v) in stresses
            vf = Float64(v)
            if vf > best; best = vf; best_id = eid; end
        end
    end
    return best, best_id
end

# ---- SOL 106 (nonlinear static) -----------------------------------------

function _report_sol106_section(io, results)
    println(io, "## SOL 106 — Nonlinear Static Results")
    println(io)
    subcases = _report_safe_get(results, "subcases", [])
    if isempty(subcases)
        println(io, "_No subcases solved._\n")
        return
    end
    for sc in subcases
        sid = _report_safe_get(sc, "sid", "?")
        println(io, "### Subcase ", sid)
        println(io)
        _report_write_static_quality(io, sc)
        nld = _report_safe_get(sc, "nonlinear_diagnostics", Dict{String,Any}())
        if !isempty(nld)
            println(io, "**Nonlinear convergence**")
            println(io)
            println(io, "| Quantity | Value |")
            println(io, "|---|---:|")
            println(io, "| Scheme | `", _report_safe_get(nld, "scheme", "?"), "` |")
            println(io, "| Requested load steps | ", _report_safe_get(nld, "requested_load_step_count", 0), " |")
            println(io, "| Accepted load steps  | ", _report_safe_get(nld, "accepted_load_step_count", 0), " |")
            println(io, "| Max iter / step      | ", _report_safe_get(nld, "max_iterations_per_step", 0), " |")
            println(io, "| Step tolerance       | ", _report_fmt_sci(_report_safe_get(nld, "tolerance", 0.0)), " |")
            println(io, "| Residual tolerance   | ", _report_fmt_sci(_report_safe_get(nld, "residual_tolerance", 0.0)), " |")
            history = _report_safe_get(nld, "load_steps", [])
            if !isempty(history)
                last_step = history[end]
                println(io, "| Last step load scale | ", _report_fmt_float(_report_safe_get(last_step, "load_scale", 0.0); digits=4), " |")
                println(io, "| Last step final rel-residual | ", _report_fmt_sci(_report_safe_get(last_step, "final_relative_residual", 0.0)), " |")
                println(io, "| Last step converged? | ", _report_safe_get(last_step, "converged", false), " |")
            end
            println(io)
        end
        println(io)
    end
end

# ---- SOL 103 (normal modes) ---------------------------------------------

function _report_sol103_section(io, results)
    println(io, "## SOL 103 — Normal Modes Results")
    println(io)
    modal_subcases = _report_safe_get(results, "subcases", [])
    if isempty(modal_subcases)
        eigenvalues = _report_safe_get(results, "eigenvalues", Float64[])
        frequencies = _report_safe_get(results, "frequencies", Float64[])
        if isempty(frequencies)
            println(io, "_No modes found._\n")
            return
        end
        _report_modal_table(io, eigenvalues, frequencies, nothing, length(frequencies))
        return
    end

    for sc in modal_subcases
        sid = _report_safe_get(sc, "sid", "?")
        method_id = _report_safe_get(sc, "method_id", nothing)
        requested = Int(_report_safe_get(sc, "requested_modes", 0))
        eigenvalues = _report_safe_get(sc, "eigenvalues", Float64[])
        frequencies = _report_safe_get(sc, "frequencies", Float64[])
        meff = _report_safe_get(sc, "modal_effective_mass", [])
        wall = _report_safe_get(sc, "wall_seconds", nothing)

        println(io, "### Subcase ", sid,
                isnothing(method_id) ? "" : " (METHOD=$(method_id))",
                " — requested $(requested) mode$(requested == 1 ? "" : "s")")
        println(io)
        if !isnothing(wall)
            println(io, "_Solve wall time: ", _report_fmt_time(wall), "_\n")
        end
        if isempty(frequencies)
            println(io, "_No modes found for this subcase._\n")
            continue
        end
        _report_modal_table(io, eigenvalues, frequencies, meff, requested)
        println(io)
    end
end

function _report_modal_table(io, eigenvalues, frequencies, meff, requested::Int)
    n_available = min(length(eigenvalues), length(frequencies))
    n_show = requested > 0 ? min(requested, n_available) : n_available
    n_show > 0 || return

    has_meff = meff isa AbstractVector && !isempty(meff)
    if has_meff
        println(io, "| Mode | Eigenvalue ω² (rad²/s²) | Frequency (Hz) | Period (s) | Meff X | Meff Y | Meff Z |")
        println(io, "|---:|---:|---:|---:|---:|---:|---:|")
    else
        println(io, "| Mode | Eigenvalue ω² (rad²/s²) | Frequency (Hz) | Period (s) |")
        println(io, "|---:|---:|---:|---:|")
    end
    for i in 1:n_show
        f = Float64(frequencies[i])
        lam = Float64(eigenvalues[i])
        T = f > 1e-30 ? 1.0 / f : Inf
        if has_meff && i <= length(meff)
            m = meff[i]
            println(io, "| ", i, " | ",
                    _report_fmt_sci(lam), " | ",
                    _report_fmt_float(f; digits=4), " | ",
                    _report_fmt_sci(T), " | ",
                    _report_fmt_sci(_report_safe_get(m, "meff_x", 0.0)), " | ",
                    _report_fmt_sci(_report_safe_get(m, "meff_y", 0.0)), " | ",
                    _report_fmt_sci(_report_safe_get(m, "meff_z", 0.0)), " |")
        else
            println(io, "| ", i, " | ",
                    _report_fmt_sci(lam), " | ",
                    _report_fmt_float(f; digits=4), " | ",
                    _report_fmt_sci(T), " |")
        end
    end
    if n_available > n_show
        println(io, "\n_", n_available - n_show, " additional mode(s) returned beyond the EIGRL request are omitted._")
    end
end

# ---- SOL 105 (linear buckling) ------------------------------------------

function _report_sol105_section(io, results)
    println(io, "## SOL 105 — Linear Buckling Results")
    println(io)
    diags = _report_safe_get(results, "solver_diagnostics", [])
    if !(diags isa AbstractVector) || isempty(diags)
        eigenvalues = _report_safe_get(results, "eigenvalues", Float64[])
        if isempty(eigenvalues)
            println(io, "_No buckling modes found._\n")
            return
        end
        _report_buckling_table(io, eigenvalues, length(eigenvalues))
        return
    end

    for entry in diags
        buck_sid = _report_safe_get(entry, "buckling_subcase", "?")
        stat_sid = _report_safe_get(entry, "static_subcase", "?")
        requested = Int(_report_safe_get(entry, "num_modes_requested", 0))
        has_range = Bool(_report_safe_get(entry, "eigrl_has_range", false))
        v1 = Float64(_report_safe_get(entry, "eigrl_v1", 0.0))
        v2 = Float64(_report_safe_get(entry, "eigrl_v2", 0.0))
        eigenvalues = _report_safe_get(entry, "eigenvalues", Float64[])
        wall = _report_safe_get(entry, "wall_seconds", nothing)
        header = "### Buckling subcase $(buck_sid) (STATSUB=$(stat_sid))"
        if has_range
            header *= " — EIGRL range [$(_report_fmt_sci(v1)), $(_report_fmt_sci(v2))], ND=$(requested)"
        else
            header *= " — requested $(requested) mode$(requested == 1 ? "" : "s")"
        end
        println(io, header)
        println(io)
        if !isnothing(wall)
            println(io, "_Solve wall time: ", _report_fmt_time(wall), "_\n")
        end
        phase_timings = _report_safe_get(entry, "phase_timings", nothing)
        kg_timings = _report_safe_get(entry, "kg_timings", nothing)
        details = _report_safe_get(entry, "details", Dict{String,Any}())
        inner_timings = details isa AbstractDict ? _report_safe_get(details, "timings", nothing) : nothing
        if phase_timings isa AbstractDict || kg_timings isa AbstractDict || inner_timings isa AbstractDict
            println(io, "| Timing detail | Wall time |")
            println(io, "|---|---:|")
            if phase_timings isa AbstractDict
                for key in ("static_reference_solve", "kg_assembly", "buckling_eigensolve")
                    haskey(phase_timings, key) || continue
                    println(io, "| ", key, " | ", _report_fmt_time(phase_timings[key]), " |")
                end
            end
            if kg_timings isa AbstractDict
                for key in ("setup", "shells", "bars_beams", "rods", "solids", "constraint_redistribution", "sparse_build")
                    haskey(kg_timings, key) || continue
                    println(io, "| kg_", key, " | ", _report_fmt_time(kg_timings[key]), " |")
                end
            end
            if inner_timings isa AbstractDict
                for key in ("prepare_context", "slice_free_matrices", "symmetry_checks", "eigensolver_search", "range_augmentation", "localization_filter", "expand_modes", "postprocess_filter_expand")
                    haskey(inner_timings, key) || continue
                    println(io, "| buckling_", key, " | ", _report_fmt_time(inner_timings[key]), " |")
                end
            end
            println(io)
        end
        if isempty(eigenvalues)
            println(io, "_No buckling modes found for this subcase._\n")
            continue
        end
        _report_buckling_table(io, eigenvalues, requested, has_range)
        println(io)
    end
end

function _report_buckling_table(io, eigenvalues, requested::Int, has_range::Bool=false)
    n_available = length(eigenvalues)
    # For range queries: show every returned mode — they all lie inside [V1,V2].
    # For ND-only queries: truncate to the requested count; extras are convergence
    # buffer that we don't need to surface.
    n_show = has_range ? n_available : (requested > 0 ? min(requested, n_available) : n_available)
    println(io, "| Mode | Load factor λ |")
    println(io, "|---:|---:|")
    for i in 1:n_show
        println(io, "| ", i, " | ", _report_fmt_float(Float64(eigenvalues[i]); digits=6), " |")
    end
    if has_range
        println(io, "\n_All ", n_show, " eigenvalue", n_show == 1 ? "" : "s",
                " lie inside the EIGRL V1..V2 range._")
    elseif n_available > n_show
        println(io, "\n_", n_available - n_show,
                " extra eigenvalue(s) were computed for convergence robustness and are not reported._")
    end
end

# ---- SOL 200 (optimization) ---------------------------------------------

function _report_sol200_section(io, results)
    println(io, "## SOL 200 — Design Optimization Results")
    println(io)
    opt = _report_safe_get(results, "optimization", Dict{String,Any}())
    route = _report_safe_get(results, "route_summary", Dict{String,Any}())

    println(io, "**Optimization summary**")
    println(io)
    println(io, "| Quantity | Value |")
    println(io, "|---|---:|")
    println(io, "| Objective         | `", _report_safe_get(opt, "objective", "?"), "` |")
    println(io, "| Iterations        | ", _report_safe_get(opt, "n_iter", 0), " |")
    println(io, "| Converged         | ", _report_safe_get(opt, "converged", false), " |")
    println(io, "| Termination       | ", _report_safe_get(opt, "termination_reason", ""), " |")
    println(io, "| Design variables  | ", _report_safe_get(opt, "design_variable_count", 0), " |")
    println(io, "| Initial mass      | ", _report_fmt_sci(_report_safe_get(opt, "mass_initial", 0.0)), " |")
    println(io, "| Target mass       | ", _report_fmt_sci(_report_safe_get(opt, "mass_target", 0.0)), " |")
    println(io, "| Final mass        | ", _report_fmt_sci(_report_safe_get(opt, "final_mass", 0.0)), " |")
    println(io, "| Mass ratio (final/initial) | ", _report_fmt_float(_report_safe_get(opt, "mass_ratio", 0.0); digits=4), " |")
    forward_sol = _report_safe_get(results, "forward_sol_type", 0)
    println(io, "| Forward SOL type  | ", forward_sol, " |")
    for (k, v) in route
        println(io, "| route: ", k, " | ", v, " |")
    end
    println(io)

    history = _report_safe_get(opt, "history", [])
    if history isa AbstractVector && !isempty(history)
        println(io, "**Objective history** (", length(history), " point", length(history) == 1 ? "" : "s", ")")
        println(io)
        println(io, "| Iter | Objective |")
        println(io, "|---:|---:|")
        n = length(history)
        show_idx = if n <= 20
            collect(1:n)
        else
            vcat(1:6, [round(Int, i) for i in range(7, stop=n-6, length=8)], n-5:n) |> unique |> sort
        end
        for (i, row) in enumerate(history)
            i in show_idx || continue
            obj = row isa AbstractDict ? _report_safe_get(row, "objective", row) : row
            println(io, "| ", i, " | ", _report_fmt_sci(Float64(obj)), " |")
        end
        println(io)
    end

    forward_results = _report_safe_get(results, "forward_results", nothing)
    if forward_results isa AbstractDict
        fs_type = Int(_report_safe_get(forward_results, "sol_type", 0))
        println(io, "---\n\n## Forward-run results at final design (SOL ", fs_type, ")")
        println(io)
        if fs_type == 101
            _report_sol101_section(io, forward_results)
        elseif fs_type == 103
            _report_sol103_section(io, forward_results)
        elseif fs_type == 105
            _report_sol105_section(io, forward_results)
        elseif fs_type == 106
            _report_sol106_section(io, forward_results)
        else
            println(io, "_No tailored section for this forward SOL type._\n")
        end
    end
end
